/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package p_final;

import javax.swing.JOptionPane;
//para meter la tabal tengo que importar las tablas
import javax.swing.table.*;
import java.text.DecimalFormat;

/**
 *
 * @author JESUS ALBERTO
 */
public class f_Nota extends javax.swing.JFrame {
    /**
     * Creates new form f_Nota
     */
    String mascara = "#,##";
    DecimalFormat formato = new DecimalFormat(mascara);
    //vector
    Object [] v_datos = new Object[8];
    //tabla
    DefaultTableModel tabla_modelo; //variable tipo tabla, tiene una tabla
    
    public f_Nota() {
        initComponents();
        tabla_modelo = (DefaultTableModel)T_notas.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        T_notas = new javax.swing.JTable();
        tb_nombre = new javax.swing.JTextField();
        cb_pilo = new javax.swing.JComboBox<>();
        tb_n1 = new javax.swing.JTextField();
        tb_n2 = new javax.swing.JTextField();
        tb_n3 = new javax.swing.JTextField();
        tb_DEF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tb_n4 = new javax.swing.JTextField();
        b_eliminar = new javax.swing.JButton();
        b_calcular_df1 = new javax.swing.JButton();
        b_agregar1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REPORTE NOTAS 2022");
        setName("f_reporte_nota"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("Nombre: ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Pilo:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Nota 1:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Nota 2:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Nota 3:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Nota 4:");

        T_notas.setBackground(new java.awt.Color(153, 255, 153));
        T_notas.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        T_notas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Pilo", "N 1", "N 2", "N 3", "N 4", "DEF", "GANA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        T_notas.setName(""); // NOI18N
        jScrollPane1.setViewportView(T_notas);

        tb_nombre.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tb_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_nombreActionPerformed(evt);
            }
        });

        cb_pilo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cb_pilo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));

        tb_n1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        tb_n2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        tb_n3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tb_n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_n3ActionPerformed(evt);
            }
        });

        tb_DEF.setEditable(false);
        tb_DEF.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tb_DEF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_DEFActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("Definitiva:");

        tb_n4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tb_n4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_n4ActionPerformed(evt);
            }
        });

        b_eliminar.setBackground(new java.awt.Color(255, 102, 102));
        b_eliminar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        b_eliminar.setText("Eliminar de la planilla");
        b_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_eliminarActionPerformed(evt);
            }
        });

        b_calcular_df1.setBackground(new java.awt.Color(51, 255, 0));
        b_calcular_df1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        b_calcular_df1.setText("Calcular_Definitiva");
        b_calcular_df1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_calcular_df1ActionPerformed(evt);
            }
        });

        b_agregar1.setBackground(new java.awt.Color(51, 255, 0));
        b_agregar1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        b_agregar1.setText("Agregar a Planilla");
        b_agregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_agregar1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CALCULAR DEFINITIVA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tb_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cb_pilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tb_n1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tb_n2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(tb_n3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(tb_n4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(tb_DEF, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b_calcular_df1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_agregar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(b_calcular_df1)
                        .addGap(18, 18, 18)
                        .addComponent(b_agregar1)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tb_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cb_pilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_n1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_DEF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_n3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_n2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_n4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_eliminar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_n3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_n3ActionPerformed

    private void tb_n4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_n4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_n4ActionPerformed

    private void tb_DEFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_DEFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_DEFActionPerformed

    private void b_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_eliminarActionPerformed
        // TODO add your handling code here:
        try {
            int fila_sel = -1;
            int arrepentido = -1;
            
            fila_sel = T_notas.getSelectedRow();
            if(fila_sel == -1){
                JOptionPane.showMessageDialog(null, "Debe seleccionar una fila para eliminar");
            }
            
            else{
                arrepentido = JOptionPane.showConfirmDialog(null, "Esta segurode remover la fila seleccionada?");
                if(arrepentido == JOptionPane.YES_OPTION){
                    tabla_modelo.removeRow(fila_sel);
                }
                
            }
            
        }
        
        catch (Exception error) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error eliminando registro en la tabla\n" + error);
            
        }
        
        
    }//GEN-LAST:event_b_eliminarActionPerformed

    private void b_calcular_df1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_calcular_df1ActionPerformed
        // TODO add your handling code here:
        
        try {
            float definitiva = 0;
            if(tb_n1.getText().isEmpty()==false  && Float.parseFloat(tb_n1.getText()) >= 0 && Float.parseFloat(tb_n1.getText()) <= 5
                    && tb_n2.getText().isEmpty()==false  && Float.parseFloat(tb_n2.getText()) >= 0 && Float.parseFloat(tb_n2.getText()) <= 5
                    && tb_n3.getText().isEmpty()==false  && Float.parseFloat(tb_n3.getText()) >= 0 && Float.parseFloat(tb_n3.getText()) <= 5
                    && tb_n4.getText().isEmpty()==false  && Float.parseFloat(tb_n4.getText()) >= 0 && Float.parseFloat(tb_n4.getText()) <= 5
            ){
                definitiva = (Float.parseFloat(tb_n1.getText())+Float.parseFloat(tb_n2.getText()) 
                        +Float.parseFloat(tb_n3.getText())+ Float.parseFloat(tb_n4.getText())) / 4;
                
                tb_DEF.setText(String.valueOf(formato.format((definitiva))));
                tb_n1.setEditable(false);
                tb_n2.setEditable(false);
                tb_n3.setEditable(false);
                tb_n4.setEditable(false);
                
            }
            
            else
                JOptionPane.showMessageDialog(null, "Revise los datos\n");
        }
        
        catch (Exception error) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error calculando nota\n" + error);
        }
        
        
        
    }//GEN-LAST:event_b_calcular_df1ActionPerformed

    private void b_agregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_agregar1ActionPerformed
        // TODO add your handling code here:
        
        try {
            if(tb_nombre.getText().isEmpty()==false
               && tb_n1.getText().isEmpty()==false
               && tb_n2.getText().isEmpty()==false
               && tb_n3.getText().isEmpty()==false
               && tb_n4.getText().isEmpty()==false
               && tb_DEF.getText().isEmpty()==false){
                
                v_datos[0] = tb_nombre.getText();
                v_datos[1] = cb_pilo.getSelectedItem();
                v_datos[2] = Float.parseFloat(tb_n1.getText()); //en la tabla la declaramos como float, recuerda
                v_datos[3] = Float.parseFloat(tb_n2.getText()); //en la tabla la declaramos como float, recuerda
                v_datos[4] = Float.parseFloat(tb_n3.getText()); //en la tabla la declaramos como float, recuerda
                v_datos[5] = Float.parseFloat(tb_n4.getText()); //en la tabla la declaramos como float, recuerda
                v_datos[6] = Float.parseFloat(tb_DEF.getText());
                if(Float.parseFloat(tb_DEF.getText())>=3){
                    v_datos[7]="SI";
                }
                else{
                    v_datos[7]="NO";
                }
                
                tabla_modelo.addRow(v_datos);
                Limpiar_campos();
            }
        }
        
        catch (Exception error) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error en el boton agregar pantilla\n" + error);
        } 
        
    
    }//GEN-LAST:event_b_agregar1ActionPerformed
    
    private void Limpiar_campos(){
        try {
            tb_nombre.setText("");
            cb_pilo.setSelectedIndex(0);
            tb_n1.setText("");
            tb_n2.setText("");
            tb_n3.setText("");
            tb_n4.setText("");
            tb_DEF.setText("");
            
            
            tb_n1.setEditable(true);
            tb_n2.setEditable(true);
            tb_n3.setEditable(true);
            tb_n4.setEditable(true);
            
            tb_nombre.grabFocus();
            
        }
        
        catch (Exception error) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error en Limpiar_campos \n" + error);
            
        }
        
    }
    
    
    private void tb_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_nombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(f_Nota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(f_Nota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(f_Nota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f_Nota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f_Nota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable T_notas;
    private javax.swing.JButton b_agregar1;
    private javax.swing.JButton b_calcular_df1;
    private javax.swing.JButton b_eliminar;
    private javax.swing.JComboBox<String> cb_pilo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tb_DEF;
    private javax.swing.JTextField tb_n1;
    private javax.swing.JTextField tb_n2;
    private javax.swing.JTextField tb_n3;
    private javax.swing.JTextField tb_n4;
    private javax.swing.JTextField tb_nombre;
    // End of variables declaration//GEN-END:variables
}
